export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const ERROR = "ERROR"; //For Any ERRORS in actions it's return error
export const REMOVE_ERROR = "REMOVE_ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const ALL_USERS = "ALL_USERS";
export const CHANGE_PWD_FAIL = "CHANGE_PWD_FAIL";

export const MONTH_EXP_CNT = "MONTH_EXP_CNT";
export const YEAR_EXP_CNT = "YEAR_EXP_CNT";
export const EXP_REPORT = "EXP_REPORT";
export const GET_DELAYS = "GET_DELAYS";
export const GET_DOORNUMBER = "GET_DOORNUMBER";
export const ADD_USER_INIT = "ADD_USER_INIT";
export const GET_ALL_USER = "GET_ALL_USER";
export const OTP_SENT = "OTP_SENT";
export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";
export const FINAL_DATA_REP = "FINAL_DATA_REP";

///NEW
export const PAYMENT_MODE = "PAYMENT_MODE";
export const LEAVE_TYPECAT_MODE = "LEAVE_TYPECAT_MODE";

export const ALL_EMPLOYEE = "ALL_EMPLOYEE";
export const SELECTED_EMP = "SELECTED_EMP";

export const ACTIVE_EMPLOYEE = "ACTIVE_EMPLOYEE";
export const USER_GROUPS = "USER_GROUPS";
export const ALL_CLIENTS = "ALL_CLIENTS";
export const ACTIVE_CLIENTS = "ACTIVE_CLIENTS";
export const ALL_DEPARTMENT = "ALL_DEPARTMENT";
export const ALL_DESIGNATION = "ALL_DESIGNATION";
export const ACTIVE_DESIGNATION = "ACTIVE_DESIGNATION";
export const ALL_MENUS = "ALL_MENUS";
export const ACTIVE_MENUS = "ACTIVE_MENUS";
export const ALL_RIGHTS = "ALL_RIGHTS";
export const ALL_PROJECT_STATUS = "ALL_PROJECT_STATUS";
export const ALL_FOLDER_NAMES = "ALL_FOLDER_NAMES";
export const ACTIVE_PROJECT_STATUS = "ACTIVE_PROJECT_STATUS";
export const ACTIVE_CLIENT_FILTER = "ACTIVE_CLIENT_FILTER";
export const JOB_QUEUE_PROJECTS = "JOB_QUEUE_PROJECTS";
export const DAILY_JOBSHEET_PROJECTS = "DAILY_JOBSHEET_PROJECTS";
export const GET_ALL_CHANGES = "GET_ALL_CHANGES";
export const LAST_ENTERED_EMP_CODE = "LAST_ENTERED_EMP_CODE";
export const ALL_DJS_CLIENTS = "ALL_DJS_CLIENTS";
export const GET_LATEST_CHANGES = "GET_LATEST_CHANGES";
export const UNVERIFIED_PROJECTS = "UNVERIFIED_PROJECTS";
export const ALL_VERF_CLIENTS = "ALL_VERF_CLIENTS";
export const ALL_STAFF_NAMES = "ALL_STAFF_NAMES";
export const ALL_STATUS_VERIFICATION = "ALL_STATUS_VERIFICATION";
export const ALL_FEEDBACK = "ALL_FEEDBACK";
export const ALL_DELETED_PROJECTS = "ALL_DELETED_PROJECTS";
export const AMENDMENT_PROJECTS = "AMENDMENT_PROJECTS";
export const AMENDMENT_HISTORY_PROJECTS = "AMENDMENT_HISTORY_PROJECTS";
export const AMENDMENT_LAST_HISTORY_PROJECTS =
  "AMENDMENT_LAST_HISTORY_PROJECTS";
export const AMENDMENT_LAST_COUNTER = "AMENDMENT_LAST_COUNTER";
export const SELECTED_CLIENT_DATA = "SELECTED_CLIENT_DATA";
export const LEAVES = "LEAVES";
export const GET_LEAVES_STAFF = "GET_LEAVES_STAFF";
export const MARKETING_EMPLOYEE = "MARKETING_EMPLOYEE";

//CT

export const ALL_COUNTRIES = "ALL_COUNTRIES";
export const ALL_STATES = "ALL_STATES";
export const ALL_DISTRICTS = "ALL_DISTRICTS";
export const ACTIVE_COUNTRY = "ACTIVE_COUNTRY";
export const ACTIVE_STATE = "ACTIVE_STATE";
export const ACTIVE_DISTRICTS = "ACTIVE_DISTRICTS";
export const STATES = "STATES";
export const ALL_LEADS = "ALL_LEADS";
export const ALL_LEADS_DD = "ALL_LEADS_DD";
export const LAST_MSG = "LAST_MSG";
export const CALLHISTORY = "CALLHISTORY";

export const GET_ALL_LEADS = "GET_ALL_LEADS";
export const GET_ALL_LEADS_DD = "GET_ALL_LEADS_DD";
export const ALL_DCT_CLIENTS = "ALL_DCT_CLIENTS";
export const ALL_DCT_CLIENTS_DD = "ALL_DCT_CLIENTS_DD";
export const DCT_CLIENTS = "DCT_CLIENTS";
export const DCT_CLIENTS_DD = "DCT_CLIENTS_DD";
export const ALL_DCT_CALLS = "ALL_DCT_CALLS";
export const ALL_DCT_CALLS_EMP = "ALL_DCT_CALLS_EMP";
export const ALL_LEADS_EMP = "ALL_LEADS_EMP";
export const GET_ALL_LEADS_EMP = "GET_ALL_LEADS_EMP";
export const ALL_DCT_CLIENTS_EMP = "ALL_DCT_CLIENTS_EMP";
export const DCT_CLIENTS_EMP = "DCT_CLIENTS_EMP";
export const GET_LEADS_LIST = "GET_LEADS_LIST";
export const GET_SELECTED_LEADS = "GET_SELECTED_LEADS";
export const GET_STAFF_DATA = "GET_STAFF_DATA";

//SCT
export const ALL_SCT_LEADS = "ALL_SCT_LEADS";
export const ALL_SCT_LEADS_DD = "ALL_SCT_LEADS_DD";
export const ALL_SCT_LEADS_EMP = "ALL_SCT_LEADS_EMP";
export const SCTCALLHISTORY = "SCTCALLHISTORY";
export const GET_ALL_SCT_LEADS = "GET_ALL_SCT_LEADS";
export const GET_ALL_SCT_LEADS_DD = "GET_ALL_SCT_LEADS_DD";
export const GET_ALL_SCT_LEADS_EMP = "GET_ALL_SCT_LEADS_EMP";
export const SCT_LAST_MSG = "SCT_LAST_MSG";
export const ALL_DEMOS = "ALL_DEMOS";
export const SCHEDULED_DEMOS = "SCHEDULED_DEMOS";
export const ALL_SCT_CALLS = "ALL_SCT_CALLS";
export const ALL_SCT_CALLS_EMP = "ALL_SCT_CALLS_EMP";
export const DEMO_STATES = "DEMO_STATES";
export const DEMO_LEADS = "DEMO_LEADS";
export const DEMO_CHECK = "DEMO_CHECK";
export const SCT_CLIENTS = "SCT_CLIENTS";
export const SCT_CLIENTS_DD = "SCT_CLIENTS_DD";
export const SCT_CLIENTS_EMP = "SCT_CLIENTS_EMP";
export const PO_PRINT = "PO_PRINT";
export const GET_SCT_STAFF_DATA = "GET_SCT_STAFF_DATA";

//SETTINGS
export const ALL_COMPANY_DETAILS = "ALL_COMPANY_DETAILS";
export const ALL_SCT_PROJECT = "ALL_SCT_PROJECT";
export const SCT_PROJECT = "SCT_PROJECT";
