export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const ALL_USERS = "ALL_USERS";
export const TENANT_ADD_INIT = "TENANT_ADD_INIT";
export const SHOP_ADD_INIT = "SHOP_ADD_INIT";
export const AGREEMENT_ADD_INIT = "AGREEMENT_ADD_INIT";

export const CHANGE_PWD_FAIL = "CHANGE_PWD_FAIL";

export const TENANT_FEEDBACK_ERROR = "TENANT_FEEDBACK_ERROR";
export const GET_ALL_SHOPS = "GET_ALL_SHOPS";
export const GET_ALL_TENANTS = "GET_ALL_TENANTS";
export const GET_ALL_SETTINGS = "GET_ALL_SETTINGS";

export const GET_DOORNOS = "GET_DOORNOS";
export const NEW_TENENTDETAILS = "NEW_TENENTDETAILS";

export const MONTH_EXP_CNT = "MONTH_EXP_CNT";
export const YEAR_EXP_CNT = "YEAR_EXP_CNT";
export const EXP_REPORT = "EXP_REPORT";
export const GET_DELAYS = "GET_DELAYS";
export const GET_DOORNUMBER = "GET_DOORNUMBER";
export const ADD_USER_INIT = "ADD_USER_INIT";
export const GET_ALL_USER = "GET_ALL_USER";
export const OTP_SENT = "OTP_SENT";
export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";
export const FINAL_DATA_REP = "FINAL_DATA_REP";

///NEW
export const PAYMENT_MODE = "PAYMENT_MODE";
export const ALL_EMPLOYEE = "ALL_EMPLOYEE";
export const SELECTED_EMP = "SELECTED_EMP";

export const ACTIVE_EMPLOYEE = "ACTIVE_EMPLOYEE";
export const USER_GROUPS = "USER_GROUPS";
export const ALL_CLIENTS = "ALL_CLIENTS";
export const ACTIVE_CLIENTS = "ACTIVE_CLIENTS";
export const ALL_DEPARTMENT = "ALL_DEPARTMENT";
export const ALL_DESIGNATION = "ALL_DESIGNATION";
export const ACTIVE_DESIGNATION = "ACTIVE_DESIGNATION";
export const ALL_MENUS = "ALL_MENUS";
export const ACTIVE_MENUS = "ACTIVE_MENUS";
export const ALL_RIGHTS = "ALL_RIGHTS";
export const ALL_PROJECT_STATUS = "ALL_PROJECT_STATUS";
export const ALL_FOLDER_NAMES = "ALL_FOLDER_NAMES";
export const ACTIVE_PROJECT_STATUS = "ACTIVE_PROJECT_STATUS";
export const ACTIVE_CLIENT_FILTER = "ACTIVE_CLIENT_FILTER";
export const JOB_QUEUE_PROJECTS = "JOB_QUEUE_PROJECTS";
export const DAILY_JOBSHEET_PROJECTS = "DAILY_JOBSHEET_PROJECTS";
export const GET_ALL_CHANGES = "GET_ALL_CHANGES";
export const LAST_ENTERED_EMP_CODE = "LAST_ENTERED_EMP_CODE";
export const ALL_DJS_CLIENTS = "ALL_DJS_CLIENTS";
export const GET_LATEST_CHANGES = "GET_LATEST_CHANGES";
export const UNVERIFIED_PROJECTS = "UNVERIFIED_PROJECTS";
export const ALL_VERF_CLIENTS = "ALL_VERF_CLIENTS";
export const ALL_STAFF_NAMES = "ALL_STAFF_NAMES";
export const ALL_STATUS_VERIFICATION = "ALL_STATUS_VERIFICATION";
export const ALL_FEEDBACK = "ALL_FEEDBACK";
export const ALL_DELETED_PROJECTS = "ALL_DELETED_PROJECTS";
export const AMENDMENT_PROJECTS = "AMENDMENT_PROJECTS";
export const AMENDMENT_HISTORY_PROJECTS = "AMENDMENT_HISTORY_PROJECTS";
export const AMENDMENT_LAST_HISTORY_PROJECTS =
  "AMENDMENT_LAST_HISTORY_PROJECTS";
export const AMENDMENT_LAST_COUNTER = "AMENDMENT_LAST_COUNTER";
export const SELECTED_CLIENT_DATA = "SELECTED_CLIENT_DATA";
